config/routes.rb
Rails.application.routes.draw do

  resources :teams
  get '/teams/by_category/:category' => 'teams#by_category'
  root 'static_pages#home'

  get 'static_pages/home'
  get 'overview' => 'static_pages#overview'
  get 'static_pages/about'

  get '/rank_participants/check_order'
  get '/rank_participants/undolist'
  patch '/rank_participants/:id/undo_deletion' => 'rank_participants#undo_deletion'

  resources :rank_participants

  get '/ranks/auto' => 'ranks#auto'
  get '/ranks/update_nums' => 'ranks#update_nums'
  get '/ranks/next_rank' => 'ranks#next_rank'
  get '/waves/auto' => 'waves#auto'
  get '/waves/update_nums' => 'waves#update_nums'

  get '/ranks/undolist'
  patch '/ranks/:id/undo_deletion' => 'ranks#undo_deletion'
  resources :ranks

  get '/waves/undolist'
  patch '/waves/:id/undo_deletion' => 'waves#undo_deletion'
  resources :waves

  get '/participants/match_rank'
  get '/participants/undolist'
  get '/participants/unfinished'
  patch '/participants/update_wave_by_bib_number/:bib_number/:wave_number' => 'participants#update_wave_by_bib_number'
  get '/participants/by_wave/:wave_number' => 'participants#by_wave'
  patch '/participants/:id/undo_deletion' => 'participants#undo_deletion'
  resources :participants do
    collection do
      get :search_bib
    end
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @latest_wave_number = ((Wave.last.try(:wave_number) || 0) + 1).to_s
  end

  def overview
  end

  def about
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<h1>About</h1>

<h2> Built with Ruby on Rails </h2>

app/views/static_pages/home.html.erb
<h1>Home Page - Tembusu Vertical Marathon Controller</h1>

<script>


</script>

<h2> For volunteers </h2>
<%= button_to 'Assign participants to waves (Participants)', participants_path, :method => "get" %> <br>
<%= button_to 'Start a new wave (Wave)', waves_path, :method => "get"  %> <br>
<%= button_to 'Record a new end-timing (Rank-Timing)', ranks_path, :method => "get"  %> <br>
<%= button_to 'Tag participants to their rank (Rank Participants)', rank_participants_path, :method => "get"  %> <br>

<h2> Info/Monitoring Screens </h2>
<%= button_to 'List participants in particular wave', '/participants/by_wave/' + @latest_wave_number, :method => "get"  %> <br>
<%= button_to 'List unfinished participants', '/participants/unfinished', :method => "get"  %> <br>

<h2> Results </h2>
<%= button_to 'Men NUS Results', '/teams/by_category/MN', :method => "get"  %>
<%= button_to 'Men Open Results', '/teams/by_category/MO', :method => "get"  %>
<%= button_to 'Female NUS Results', '/teams/by_category/FN', :method => "get"  %>
<%= button_to 'Female Open Results', '/teams/by_category/WO', :method => "get"  %>
<%= button_to 'Couple NUS Results', '/teams/by_category/CN', :method => "get"  %>
<%= button_to 'Team NUS Results', '/teams/by_category/TN', :method => "get"  %>
<%= button_to 'Individual Participants Results', 'participants/match_rank', :method => "get"  %>

<br>
<h2> Administrative Screens (do not touch unless Yew Siang/Sri/Marvin/Yong Jie)
<br>

<%= button_to 'Overview <admin>', '/overview', :method => "get"  %> <br>

app/views/static_pages/overview.html.erb
<h1>Overview - You should only be here if you are an admin!</h1>


<embed src='/rank_participants/check_order' width=500 height=500 />
<embed src='/participants/unfinished' width=500 height=500 />
<br>
<embed src="/participants" width=500 height=500 />
<embed src="/waves" width=500 height=500 />
<embed src="/ranks" width=500 height=500 />
<embed src="/rank_participants" width=500 height=500 />
<br>
<embed src="/participants/match_rank" width=1000 height=500 />