config/routes.rb
Rails.application.routes.draw do

  resources :teams
  get '/teams/by_category/:category' => 'teams#by_category'
  root 'static_pages#home'

  get 'static_pages/home'
  get 'overview' => 'static_pages#overview'
  get 'static_pages/about'

  get '/rank_participants/check_order'
  get '/rank_participants/undolist'
  patch '/rank_participants/:id/undo_deletion' => 'rank_participants#undo_deletion'

  resources :rank_participants

  get '/ranks/auto' => 'ranks#auto'
  get '/ranks/update_nums' => 'ranks#update_nums'
  get '/ranks/next_rank' => 'ranks#next_rank'
  get '/waves/auto' => 'waves#auto'
  get '/waves/update_nums' => 'waves#update_nums'

  get '/ranks/undolist'
  patch '/ranks/:id/undo_deletion' => 'ranks#undo_deletion'
  resources :ranks

  get '/waves/undolist'
  patch '/waves/:id/undo_deletion' => 'waves#undo_deletion'
  resources :waves

  get '/participants/match_rank'
  get '/participants/undolist'
  get '/participants/unfinished'
  patch '/participants/update_wave_by_bib_number/:bib_number/:wave_number' => 'participants#update_wave_by_bib_number'
  get '/participants/by_wave/:wave_number' => 'participants#by_wave'
  patch '/participants/:id/undo_deletion' => 'participants#undo_deletion'
  resources :participants do
    collection do
      get :search_bib
    end
  end

end

app/models/participant.rb
class Participant < ActiveRecord::Base
  # Always belong to a team
  belongs_to :team

  validates :name, :bib_number, :presence => true

  validates :bib_number, :uniqueness => true

  # MTCFW - Male/Team/Couple/Female/Women, ON - Open/NUS, then 3 digits
  validates :bib_number, :format => { with: /[MTCFW][ON]\d{3}/, message: "must match regex [MTCFW][ON]\\d{3}" }

  #cannot input a wave that has already started
  #validate :wave_cannot_have_started
  #validate :limit_number_of_participants_in_wave

	#PARANOID MODE: Nothing really gets deleted
	acts_as_paranoid

  def wave_cannot_have_started
    if Wave.exists?(wave_number: wave_number)
      errors.add(:wave_number, "is not allowed. Wave has already started.")
    end
  end

  def limit_number_of_participants_in_wave
    if self.wave_number.present? && Participant.where(wave_number: self.wave_number).count >= Wave::MAX_PARTICIPANTS_IN_WAVE
      errors.add(:wave_number, "is incorrect, only #{Wave::MAX_PARTICIPANTS_IN_WAVE} people can be in one wave. Please allocate participant to the next wave.")
    end
  end

  # Gets this participant's total elapsed time to complete the race
  def get_timing
    participant = self
    rank_participant = RankParticipant.find_by(bib_number: participant.bib_number)

    rank = nil
    wave_number = nil
    end_time = nil
    start_time = nil
    time_delta = nil

    #get a wave object to check for a start time
    wave_number = participant.wave_number

    unless wave_number.blank? || !Wave.exists?(wave_number: participant.wave_number)
      start_time = Wave.find_by(wave_number: participant.wave_number).start_time

      unless rank_participant.nil?
        #if we have a participant with a rank, get the timing object to check end time
        rank = rank_participant.rank
        timing_object = Rank.find_by(rank: rank)

        unless timing_object.nil?
          #if we do have a timing object, get the end time
          end_time = timing_object.end_time
          time_delta_float_seconds = end_time - start_time
        end

      end
    end

    return time_delta_float_seconds
  end

  end

app/controllers/participants_controller.rb
require 'csv'
class ParticipantsController < ApplicationController
  before_action :set_participant, only: [:show, :edit, :update, :destroy]


  # PATCH/PUT /participants/update_wave_by_bib_number/:bib_number/:wave_number
  def update_wave_by_bib_number
    bib_number = params[:bib_number]
    wave_number = params[:wave_number]

    @participant = Participant.where(bib_number: bib_number).first

    if @participant.present?
      # Update the participant
      if @participant.update(wave_number: wave_number)
        render json: { message: "Successfully updated " + bib_number + " to be in wave " + wave_number}
      else
        render json: @participant.errors, status: :unprocessable_entity
      end
    else
      render json: { message: "Cannot find participant with that bib number!"}, status: :not_found
    end

  end

  # GET /participants
  # GET /participants.json
  def index
    #@participants = Participant.all
    @participants = Participant.order('wave_number ASC')
    @participant = Participant.new
  end

  # GET /participants/1
  # GET /participants/1.json
  def show
  end

  # GET /participants/new
  def new
    @participant = Participant.new
  end

  # GET /participants/1/edit
  def edit
  end

  def search_bib
    if params[:search]
      puts "Searching with param #{params[:search]}"
      @participant = Participant.where(bib_number: params[:search].upcase.strip).first
      unless @participant.present?
        flash[:notice] = "Participant could not be found!"
        redirect_to participants_path
      end
    else
      render plain: "No search parameter!"
    end
  end

  # Endpoint to show on a large screen - participants for the next wave
  def by_wave
    @participants = Participant.where(wave_number: params[:wave_number])
  end

  # POST /participants
  # POST /participants.json
  def create
    @participant = Participant.new(participant_params)

    respond_to do |format|
      if @participant.save
        #format.html { redirect_to @participant, notice: 'Participant was successfully created.' }
        format.html { redirect_to participants_path, notice: 'Participant was successfully created.' }
        format.json { render :show, status: :created, location: @participant }
        #format.js   { }
      else
        p @participant.errors
        format.html { render :new }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
        format.js { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /participants/1
  # PATCH/PUT /participants/1.json
  def update
    respond_to do |format|
      if @participant.update(participant_params)
        #format.html { redirect_to @participant, notice: 'Participant was successfully updated.' }
        format.html { redirect_to participants_path, notice: 'Participant was successfully updated.' }
        format.json { render :show, status: :ok, location: @participant }
      else
        format.html { render :edit }
        format.json { render json: @participant.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /participants/1
  # DELETE /participants/1.json
  def destroy
      @participant.destroy


    respond_to do |format|
      format.html { redirect_to participants_url, notice: 'Participant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  #lists ALL the deleted participants in order so that we can undo
  def undolist
    @participants = Participant.only_deleted.reverse
  end

  #controller to fully delete a participant
  def undo_deletion
    Participant.only_deleted.find(params[:id]).restore

    respond_to do |format|
      format.html { redirect_to participants_url, notice: 'Participant was successfully recovered.' }
      format.json { head :no_content }
    end
  end

  #controller to fully delete a participant
  def really_delete
    Participant.only_deleted.find(params[:id]).really_destroy!

    respond_to do |format|
      format.html { redirect_to participants_url, notice: 'Participant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def match_rank
    Time.zone = "Singapore"
=begin
    participants = Participant.all
    @names_with_ranks = {}

    participants.each do |participant|

      rp = RankParticipant.where(bib_number: participant.bib_number).first
      end_time = Rank.where(rank: rp.rank).first.end_time
      wave = Wave.where(wave_number: participant.try(:wave_number)).first

      rank = rp.rank
      start_time = wave.start_time

      time_delta = Time.at((end_time.to_f - start_time.to_f)).utc.strftime("%H:%M:%S.%3N")
      waveId = wave.wave_number


       @names_with_ranks[participant.name] = [rank, start_time.strftime("%d/%m/%Y %H:%M:%S.%3N"), end_time.strftime("%d/%m/%Y %H:%M:%S.%3N"), time_delta, wave_number]
    end
=end


    participants = Participant.order("wave_number ASC")
    @all_info = []

    participants.map do |participant|
      rank_participant = RankParticipant.find_by(bib_number: participant.bib_number)

      rank = nil
      wave_number = nil
      end_time = nil
      start_time = nil
      time_delta = nil

      #get a wave object to check for a start time
      wave_number = participant.wave_number

      unless wave_number.blank? || !Wave.exists?(wave_number: participant.wave_number)
        start_time = Wave.find_by(wave_number: participant.wave_number).start_time

        unless rank_participant.nil?
          #if we have a participant with a rank, get the timing object to check end time
          rank = rank_participant.rank
          timing_object = Rank.find_by(rank: rank)

          unless timing_object.nil?
            #if we do have a timing object, get the end time
            end_time = timing_object.end_time
            #time delta is in MINUTES
            time_delta = Time.at((end_time.to_f - start_time.to_f)).utc.strftime("%H:%M:%S.%3N")
          end

        end
      end

      #create final hash as key pointing to array of values
      @all_info << {name: participant.name,
                    rank: rank,
                    start_time: start_time.try(:strftime, "%d/%m/%Y %H:%M:%S.%3N"),
                    end_time: end_time.try(:strftime, "%d/%m/%Y %H:%M:%S.%3N"),
                    timing: time_delta || DateTime.new, wave_number: wave_number
                  }

      CSV.open("data.csv", "wb") do |csv|
        @all_info.each do |hash|
          csv << hash.values
        end
      end
    end

    p "All info!!"
    p @all_info
  end


  def unfinished
    @participants = Participant.all
    @rank_participants = RankParticipant.all

    # Select from the list of participants, those that hasn't finished the race
    # @rank_participants.any checks for any rank_participant within the @rank_participants array and returns those whose bib_number is the
    # same as participant.bib_number
    # "!" chooses the participants whose bib number isn't registered in rank_participants' bib numbers
    @unfinished_participants = @participants.select { |x| !@rank_participants.any? {
        |rank_participant| rank_participant.bib_number == x.bib_number
      } }

    # Select from the list of rank_participants those that has finished the race and got a rank registered BUT are not registered at the start
    # @participants.any checks for an participant within the @participants array and returns those whose bib_number is the
    # same as rank_participant.bib_number
    # "!" chooses the rank_participants whose bib number isn't registered in participants' bib numbers
    @unregistered_rank_participants = @rank_participants.select { |x| !@participants.any? {
        |participant| participant.bib_number == x.bib_number
      } }

  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_participant
      @participant = Participant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def participant_params
      params.require(:participant).permit(:name, :bib_number, :wave_number)
    end
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/views/participants/_form.html.erb
<%= form_for(@participant) do |f| %>
  <% if @participant.errors.any? %>
    <div id="error_explanation">
      <h2 style="color: red"><%= pluralize(@participant.errors.count, "error") %> prohibited this participant from being saved:</h2>

      <ul style="color: red">
      <% @participant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :bib_number %><br>
    <%= f.text_field :bib_number %>
  </div>
  <div class="field">
    <%= f.label :wave_number %><br>
    <%= f.number_field :wave_number, min: 1, autofocus: true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/participants/by_wave.html.erb
<script>
  function changeTiming() {
    var timing = prompt("Please enter new timing in seconds")
    sessionStorage.setItem('start_time', timing)
  }
</script>
<div class="row">

  <div class="col-xs-2"></div>
  <div class="col-xs-4">
    <h2 class="fronttitle"> Participants in Wave <%= params[:wave_number] %></h2>
    <!--<%= form_tag search_bib_participants_path, :method => 'get' do %>
      <p>
        <%= text_field_tag :search, params[:search], autofocus: true%>
        <%= submit_tag "Search", :name => nil %>
      </p>
    <% end %>-->
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Bib number</th>
          <th>Wave number</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @participants.each do |participant| %>
          <tr>
            <td><%= participant.name %></td>
            <td><%= participant.bib_number %></td>
            <td><%= participant.wave_number %></td>
            <!--<td><%= link_to 'Show', participant %></td>
            <td><%= link_to 'Edit', edit_participant_path(participant) %></td>-->
            <!--<td><%= link_to 'Destroy', participant, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>
    <div class="row">
      <div class="col-md-4"></div>
      <div class="col-md-2">
        <%= button_to('Back', "/participants/by_wave/" + (params[:wave_number].to_i - 1).to_s, {method: :get}) %>
      </div>
      <div class="col-md-2">
        <%= button_to('Next', "/participants/by_wave/" + (params[:wave_number].to_i + 1).to_s, {method: :get}) %>
      </div>
      <div class="col-md-4"></div>
    </div>
  </div>

  <div class="col-xs-4">
    <h2 class="fronttitle"> Time to start of race</h2>
    <div class="clock" style="margin:2em; width: 300px; margin-left: auto; margin-right: auto"></div>
    <div class="message"></div>
    <button class="Start">Start</button>
    <button class="Stop">Stop</button>
    <button class="Reset">Reset</button> <br> <br>
    <button class="ChangeTiming" onclick="changeTiming()">Change Timing</button>
  </div>

  <div class="col-xs-2"></div>

</div>

app/views/participants/edit.html.erb
<!--<div style="zoom: 500%">-->
<h1>Editing Participant</h1>

<%= render 'form' %>

<%= link_to 'Show', @participant %> |
<%= link_to 'Back', participants_path %>
</div>

app/views/participants/index.html.erb
<!--<div style="zoom: 500%;">-->
<h1 class = "fronttitle">Listing Participants</h1>

<!--
<%= form_for(@participant, remote: true) do |f| %>
  <% if @participant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@participant.errors.count, "error") %> prohibited this participant from being saved:</h2>

      <ul>
      <% @participant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  -->
<!--
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :bib_number %><br>
    <%= f.text_field :bib_number %>
  </div>
  <div class="field">
    <%= f.label :wave_number %><br>
    <%= f.number_field :wave_number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
-->

<!--<%= button_to 'Undo', '/participants/undolist', :method => "get" %> <br> -->

<% if flash[:notice] %>
  <div class="notice" style='color: red; font-size: 24px'><%= flash[:notice] %></div>
<% end %>

<%= form_tag search_bib_participants_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search], autofocus: true%>
    <%= submit_tag "Search Bib Number", :name => nil%>
  </p>
<% end %>


<table>
  <thead>
    <tr>
      <th> <center> Name </center> </th>
      <th>Bib number</th>
      <th>Wave number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @participants.each do |participant| %>
      <tr>
        <td><%= participant.name %></td>
        <td><%= participant.bib_number %></td>
        <td><%= participant.wave_number %></td>
        <!--<td><%= link_to 'Show', participant %></td>-->
        <td><%= link_to 'Edit', edit_participant_path(participant) %></td>
        <!--<td><%= link_to 'Destroy', participant, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!-- <%= link_to 'New Participant', new_participant_path %> -->

<br>
<h2 class = "fronttitle">Instructions</h2>
<p class="instructions">FOR TAGGERS</p>
<p class="instructions">1) Scan Bib number and make sure partipicant's Bib number is reflected, double check to make sure the barcode scanning has been done correctly.</p>
<p class="instructions"> Then click "Search Bib Number" or hit "Enter".</p>
<p class="instructions">2) Enter Wave number for the runner. Fill each Wave with <%= Wave::MAX_PARTICIPANTS_IN_WAVE %> runners, starting from Wave number 1.</p>

<h2 class = "fronttitle">Problems</h2>
<p class="instructions">1) IN CASE YOU ENTERED THE WRONG WAVE NUMBER: Click "Edit" and change to the correct Wave number.</p>
<br>
<br>
</div>

app/views/participants/match_rank.html.erb
<h1> Rank Matching </h1>
<table>
  <thead>
    <tr>

      <th>Number</th>
      <th><center> Name </center></th>
      <th><center> Waves </center></th>
      <th> <center> Rank </center></th>
      <th>Start Time</th>
      <th>End Time</th>
      <th>Timing</th>
    </tr>
  </thead>

  <tbody>
    <% count = 1 %>
    <% @all_info.sort_by{|h| h[:timing]}.each do |info| %>
      <tr>
        <td><%= count %></td>
        <% count = count + 1 %>
        <td><%= info[:name]%></td>
        <td><%= info[:wave_number] || "-" %></td>
        <td><%= info[:rank] || "-"%></td>
        <td><%= info[:start_time] || "-" %></td>
        <td><%= info[:end_time] || "-"%></td>
        <td><%= info[:timing] || "-"%></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/participants/new.html.erb
<h1>New Participant</h1>

<%= render'form' %>

<%= link_to 'Back', participants_path %>

app/views/participants/search_bib.html.erb
<!--<div style="zoom: 500%"-->
<h1>Editing Participant</h1>
<%= form_for(@participant) do |f| %>
  <% if @participant.errors.any? %>
    <div id="error_explanation">
      <h2 style="color: red"><%= pluralize(@participant.errors.count, "error") %> prohibited this participant from being saved:</h2>

      <ul style="color: red">
      <% @participant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= @participant.name %>
  </div>
  <div class="field">
    <%= f.label :bib_number %><br>
    <%= @participant.bib_number %>
  </div>
  <div class="field">
    <%= f.label :wave_number %><br>
    <%= f.number_field :wave_number, min: 1, autofocus: true%>
  </div>
  <div class="actions">
    <%= f.submit 'Update' %>
  </div>
<% end %>

<%= link_to 'Show', @participant %> |
<%= link_to 'Back', participants_path %>

</div>

app/views/participants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @participant.name %>
</p>

<p>
  <strong>Bib number:</strong>
  <%= @participant.bib_number %>
</p>

<p>
  <strong>Wave number:</strong>
  <%= @participant.wave_number %>
</p>

<%= link_to 'Edit', edit_participant_path(@participant) %> |
<%= link_to 'Back', participants_path %>

app/views/participants/undolist.html.erb
<h1> Undo List </h1>

<h1>Listing Participants</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Bib number</th>
      <th>Wave number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @participants.each do |participant| %>
      <tr>
        <td><%= participant.name %></td>
        <td><%= participant.bib_number %></td>
        <td><%= participant.wave_number %></td>
        <td><%= link_to 'Show', participant %></td>
        <td><%= link_to 'Edit', edit_participant_path(participant) %></td>
        <td><%= link_to 'Undo Deletion', "/participants/#{participant.id}/undo_deletion", method: :patch, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Destroy', "/participants/#{participant.id}/really_delete", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/participants/unfinished.html.erb
<h1 class = "fronttitle">Unfinished Participants</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Bib number</th>
      <th>Wave number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @unfinished_participants.each do |participant| %>
      <tr>
        <td><%= participant.name %></td>
        <td><%= participant.bib_number %></td>
        <td><%= participant.wave_number %></td>
        <td><%= link_to 'Show', participant %></td>
        <td><%= link_to 'Edit', edit_participant_path(participant) %></td>
        <td><%= link_to 'Destroy', participant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<h1 class = "fronttitle">Unregistered Participants</h1>

<table>
  <thead>
    <tr>
      <th>Rank</th>
      <th>Name</th>
      <th>Bib number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @unregistered_rank_participants.each do |rank_participant| %>
      <tr>
        <td><%= rank_participant.rank %></td>
        <td><%= rank_participant.name %></td>
        <td><%= rank_participant.bib_number %></td>
        <td><%= link_to 'Show', rank_participant %></td>
        <td><%= link_to 'Edit', edit_rank_participant_path(rank_participant) %></td>
        <td><%= link_to 'Destroy', rank_participant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>