config/routes.rb
Rails.application.routes.draw do

  resources :teams
  get '/teams/by_category/:category' => 'teams#by_category'
  root 'static_pages#home'

  get 'static_pages/home'
  get 'overview' => 'static_pages#overview'
  get 'static_pages/about'

  get '/rank_participants/check_order'
  get '/rank_participants/undolist'
  patch '/rank_participants/:id/undo_deletion' => 'rank_participants#undo_deletion'

  resources :rank_participants

  get '/ranks/auto' => 'ranks#auto'
  get '/ranks/update_nums' => 'ranks#update_nums'
  get '/ranks/next_rank' => 'ranks#next_rank'
  get '/waves/auto' => 'waves#auto'
  get '/waves/update_nums' => 'waves#update_nums'

  get '/ranks/undolist'
  patch '/ranks/:id/undo_deletion' => 'ranks#undo_deletion'
  resources :ranks

  get '/waves/undolist'
  patch '/waves/:id/undo_deletion' => 'waves#undo_deletion'
  resources :waves

  get '/participants/match_rank'
  get '/participants/undolist'
  get '/participants/unfinished'
  patch '/participants/update_wave_by_bib_number/:bib_number/:wave_number' => 'participants#update_wave_by_bib_number'
  get '/participants/by_wave/:wave_number' => 'participants#by_wave'
  patch '/participants/:id/undo_deletion' => 'participants#undo_deletion'
  resources :participants do
    collection do
      get :search_bib
    end
  end

end

app/models/rank_participant.rb
class RankParticipant < ActiveRecord::Base
	validates :rank, :name, :bib_number, :presence => true

  validates :rank, uniqueness: true

	#PARANOID MODE: Nothing really gets deleted
	acts_as_paranoid



end

app/controllers/rank_participants_controller.rb
class RankParticipantsController < ApplicationController
  before_action :set_rank_participant, only: [:show, :edit, :update, :destroy]
  include RankParticipantsHelper
  # GET /rank_participants
  # GET /rank_participants.json
  def index
    @rank_participants = RankParticipant.all.reverse
    @rank_participant = RankParticipant.new
    @missing = missing_numbers
  end

  # GET /rank_participants/1
  # GET /rank_participants/1.json
  def show
  end

  # GET /rank_participants/new
  def new
    @rank_participant = RankParticipant.new
  end

  # GET /rank_participants/1/edit
  def edit
  end


  # POST /rank_participants
  # POST /rank_participants.json
  def create
    if params[:commit] == "Force Submit"
      @rank_participant = RankParticipant.new(rank_participant_params)
      @rank_participant.name = "HARD CREATED!" if @rank_participant.name.blank?
      respond_to do |format|
        if @rank_participant.save
          format.html { redirect_to @rank_participant, notice: 'Rank participant was successfully created.' }
          format.json { render :show, status: :created, location: @rank_participant }
        else
          format.html { render :new }
          format.json { render json: @rank_participant.errors, status: :unprocessable_entity }
          format.js { render json: @rank_participant.errors, status: :unprocessable_entity }
        end
      end
    else
      self.soft_create(rank_participant_params)
    end

  end

  # PATCH/PUT /rank_participants/1
  # PATCH/PUT /rank_participants/1.json
  def update
    respond_to do |format|
      if @rank_participant.update(rank_participant_params)
        format.html { redirect_to @rank_participant, notice: 'Rank participant was successfully updated.' }
        format.json { render :show, status: :ok, location: @rank_participant }
      else
        format.html { render :edit }
        format.json { render json: @rank_participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rank_participants/1
  # DELETE /rank_participants/1.json
  def destroy
    @rank_participant.destroy
    respond_to do |format|
      format.html { redirect_to rank_participants_url, notice: 'Rank participant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  #lists ALL the deleted participants in order so that we can undo
  def undolist
    @rank_participants = RankParticipant.only_deleted.reverse
  end

  #controller to fully delete a participant
  def undo_deletion
    RankParticipant.only_deleted.find(params[:id]).restore

    respond_to do |format|
      format.html { redirect_to rank_participants_url, notice: 'RankParticipant was successfully recovered.' }
      format.json { head :no_content }
    end
  end

  #controller to fully delete a participant
  def really_delete
    RankParticipant.only_deleted.find(params[:id]).really_destroy!

    respond_to do |format|
      format.html { redirect_to rank_participants_url, notice: 'RankParticipant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  #checks the order of the ranks and gets the ranks that are not filled in yet
  def check_order
    rps = RankParticipant.all

    #sort the rank participants and extract an array of only the ranks (that are sorted)
    all_ranks_sorted = rps.sort_by { |x| [x.rank] }.map { |rp| rp.rank }

    #array of missing ranks
    @missing = []

    all_ranks_sorted.each_with_index do |item, index|
      if index > 0
        #difference between consecutive ranks, should be 1
        difference = all_ranks_sorted[index] - all_ranks_sorted[index - 1]

        if difference > 1
         @missing.concat(((all_ranks_sorted[index - 1] + 1)...(all_ranks_sorted[index])).to_a)
        end
      end
    end
  end
 #check existence of participant bib number before creating
    def soft_create(rank_participant_params)

      @rank_participant = RankParticipant.new(rank_participant_params)

      @rank_participant.name = Participant.where(bib_number: rank_participant_params[:bib_number]).first.name || "Cannot find name!"

      #Check for rank participant as existent in the participants list, and make sure we don't enter a cancelled
      #rank chip number
      respond_to do |format|
        if Participant.find_by(bib_number: @rank_participant.bib_number) &&
           !(missing_numbers.include?(@rank_participant.rank)) &&
           @rank_participant.save

          format.html { redirect_to @rank_participant, notice: 'Rank participant was successfully created.' }
          format.json { render :show, status: :created, location: @rank_participant }
        else
          p @rank_participant.errors
          format.html { render :new }
          format.json { render json: @rank_participant.errors, status: :unprocessable_entity }
          format.js { render json: @rank_participant.errors, status: :unprocessable_entity }
        end
      end
    end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rank_participant
      @rank_participant = RankParticipant.find(params[:id])
    end

    def cannot_register_missing_rank
      if missing_numbers.include?(self.rank)
        errors.add(:rank, "is missing! Confirm with the rank chip giver that this rank is cancelled.")
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rank_participant_params
      params.require(:rank_participant).permit(:rank, :name, :bib_number)
    end


end

app/helpers/rank_participants_helper.rb
module RankParticipantsHelper
  def missing_numbers
    if Rank.count > 0
      return (Rank.minimum(:rank)...Rank.maximum(:rank)).to_a - Rank.pluck(:rank)
    end
  end
end

app/views/rank_participants/_form.html.erb
<%= form_for(@rank_participant) do |f| %>
  <% if @rank_participant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rank_participant.errors.count, "error") %> prohibited this rank_participant from being saved:</h2>

      <ul>
      <% @rank_participant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :rank %><br>
    <%= f.number_field :rank %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :bib_number %><br>
    <%= f.text_field :bib_number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rank_participants/check_order.html.erb
<h1> Missing Ranks! </h1>

<% @missing.each do |rank| %>
  <%= rank %> <br>
<% end %>

app/views/rank_participants/edit.html.erb
<h1>Editing Rank Participant</h1>

<%= render 'form' %>

<%= link_to 'Show', @rank_participant %> |
<%= link_to 'Back', rank_participants_path %>

app/views/rank_participants/index.html.erb
<h1 class = "fronttitle">Listing Rank Participants</h1>

<h3 style="color: red"> Missing Ranks: <%= @missing %> </h3>

<%= form_for(@rank_participant, remote: true) do |f| %>
  <% if @rank_participant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rank_participant.errors.count, "error") %> prohibited this rank_participant from being saved:</h2>

      <ul>
      <% @rank_participant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :rank %><br>
    <%= f.number_field :rank %>
  </div>
  <!--
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  -->
  <div class="field">
    <%= f.label :bib_number %><br>
    <%= f.text_field :bib_number %>
  </div>
  <div class="actions">
    <%= f.submit 'Submit' %>
    <br>
    <br>
    <%= f.submit 'Force Submit' %>
  </div>
<% end %>

<%= button_to 'Undo', '/rank_participants/undolist', :method => "get" %> <br>
<p id="notice"><%= notice %></p>


<table>
  <thead>
    <tr>
      <th>Rank</th>
      <th>Name</th>
      <th>Bib number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rank_participants.each do |rank_participant| %>
      <tr>
        <td><%= rank_participant.rank %></td>
        <td><%= rank_participant.name %></td>
        <td><%= rank_participant.bib_number %></td>
        <!--<td><%= link_to 'Show', rank_participant %></td> -->
        <!--<td><%= link_to 'Edit', edit_rank_participant_path(rank_participant) %></td>-->
        <td><%= link_to 'Destroy', rank_participant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<br>
<h2 class = "fronttitle">Instructions</h2>
<p class="instructions">FOR RANK TAGGER</p>
<p class="instructions">1) Take the Rank chip of the runner. Record down their Rank (from rank chip) and Bib number</p>
<p class="instructions"> Then click "Submit" (Don't click "Force Submit")</p>
<p class="instructions"> Look at the list and ask them if their name is as shown.</p>

<h2 class = "fronttitle">Problems</h2>
<p class="instructions">1) IN CASE YOU ARE UNABLE TO SUBMIT THE FORM DUE TO ERRORS: Inform Yew Siang or Sriram</p>
<p class="instructions">2) IN CASE YOU ENTERED THE WRONG INFORMATION: Click "Edit" or "Destroy"</p>
<br>
<br>

<!--<%= link_to 'New Rank participant', new_rank_participant_path %>-->

app/views/rank_participants/new.html.erb
<h1>New Rank Participant</h1>

<%= render 'form' %>

<%= link_to 'Back', rank_participants_path %>

app/views/rank_participants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rank:</strong>
  <%= @rank_participant.rank %>
</p>

<p>
  <strong>Name:</strong>
  <%= @rank_participant.name %>
</p>

<p>
  <strong>Bib number:</strong>
  <%= @rank_participant.bib_number %>
</p>

<%= link_to 'Edit', edit_rank_participant_path(@rank_participant) %> |
<%= link_to 'Back', rank_participants_path %>

app/views/rank_participants/undolist.html.erb
<h1> Undo List </h1>

<h1>Listing Rank Participants</h1>

<table>
  <thead>
    <tr>
      <th>Rank</th>
      <th>Name</th>
      <th>Bib number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rank_participants.each do |rank_participant| %>
      <tr>
        <td><%= rank_participant.rank %></td>
        <td><%= rank_participant.name %></td>
        <td><%= rank_participant.bib_number %></td>
        <td><%= link_to 'Show', rank_participant %></td>
        <td><%= link_to 'Undo Deletion', "/rank_participants/#{rank_participant.id}/undo_deletion", method: :patch, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Destroy', "/rank_participants/#{rank_participant.id}/really_delete", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>