config/routes.rb
Rails.application.routes.draw do

  resources :teams
  get '/teams/by_category/:category' => 'teams#by_category'
  root 'static_pages#home'

  get 'static_pages/home'
  get 'overview' => 'static_pages#overview'
  get 'static_pages/about'

  get '/rank_participants/check_order'
  get '/rank_participants/undolist'
  patch '/rank_participants/:id/undo_deletion' => 'rank_participants#undo_deletion'

  resources :rank_participants

  get '/ranks/auto' => 'ranks#auto'
  get '/ranks/update_nums' => 'ranks#update_nums'
  get '/ranks/next_rank' => 'ranks#next_rank'
  get '/waves/auto' => 'waves#auto'
  get '/waves/update_nums' => 'waves#update_nums'

  get '/ranks/undolist'
  patch '/ranks/:id/undo_deletion' => 'ranks#undo_deletion'
  resources :ranks

  get '/waves/undolist'
  patch '/waves/:id/undo_deletion' => 'waves#undo_deletion'
  resources :waves

  get '/participants/match_rank'
  get '/participants/undolist'
  get '/participants/unfinished'
  patch '/participants/update_wave_by_bib_number/:bib_number/:wave_number' => 'participants#update_wave_by_bib_number'
  get '/participants/by_wave/:wave_number' => 'participants#by_wave'
  patch '/participants/:id/undo_deletion' => 'participants#undo_deletion'
  resources :participants do
    collection do
      get :search_bib
    end
  end

end

app/models/wave.rb
class Wave < ActiveRecord::Base
	validates :wave_number, :start_time, :presence => true

	#PARANOID MODE: Nothing really gets deleted
	acts_as_paranoid

    MAX_PARTICIPANTS_IN_WAVE = 5


end

app/controllers/waves_controller.rb
class WavesController < ApplicationController
  before_action :set_wave, only: [:show, :edit, :update, :destroy]

  # GET /waves
  # GET /waves.json
  def index
    @waves = Wave.all.reverse
    @wave = Wave.new
  end

  # GET /waves/1
  # GET /waves/1.json
  def show
    @participants = Participant.where(wave_number: @wave.wave_number)
  end

  # GET /waves/new
  def new
    @wave = Wave.new
  end

  # GET /waves/1/edit
  def edit
  end

  # POST /waves
  # POST /waves.json
  def create
    @wave = Wave.new(wave_params)

    respond_to do |format|
      if @wave.save
        format.html { redirect_to @wave, notice: 'Wave was successfully created.' }
        format.json { render :show, status: :created, location: @wave }
      else
        format.html { render :new }
        format.json { render json: @wave.errors, status: :unprocessable_entity }
        format.js { render json: @wave.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /waves/1
  # PATCH/PUT /waves/1.json
  def update
    respond_to do |format|
      if @wave.update(wave_params)
        format.html { redirect_to @wave, notice: 'Wave was successfully updated.' }
        format.json { render :show, status: :ok, location: @wave }
      else
        format.html { render :edit }
        format.json { render json: @wave.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /waves/1
  # DELETE /waves/1.json
  def destroy
    @wave.destroy
    respond_to do |format|
      format.html { redirect_to waves_url, notice: 'Wave was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  #lists ALL the deleted Waves in order so that we can undo
  def undolist
    @waves = Wave.only_deleted.reverse
  end

  #controller to fully delete a Wave
  def undo_deletion
    Wave.only_deleted.find(params[:id]).restore

    respond_to do |format|
      format.html { redirect_to waves_url, notice: 'Wave was successfully recovered.' }
      format.json { head :no_content }
    end
  end

  #controller to fully delete a Wave
  def really_delete
    Wave.only_deleted.find(params[:id]).really_destroy!

    respond_to do |format|
      format.html { redirect_to waves_url, notice: 'Wave was successfully destroyed.' }
      format.json { head :no_content }
    end
  end



  def auto
    @waves = Wave.all
    @new_wave = Wave.new

    # Current time
    Time.zone = "Singapore"
    time_now = Time.zone.now

    # Edit the new_wave to be added to the database
    if @waves.blank?
      @new_wave.wave_number = 1
    else
      @new_wave.wave_number = @waves.last.wave_number + 1
    end
    @new_wave.start_time = time_now
    @new_wave.created_at = time_now
    @new_wave.updated_at = time_now

    respond_to do |format|
      if @new_wave.save
        format.html { redirect_to @new_wave, notice: 'Wave was successfully created.' }
        format.json { render :show, status: :created, location: @new_wave }
      else
        format.html { render :new }
        format.json { render json: @new_wave.errors, status: :unprocessable_entity }
      end
    end
  end


  def update_nums
    @waves = Wave.all
    @new_waves = @waves.sort_by { |x| [x.start_time] }

    counter = 1
    ActiveRecord::Base.transaction do
      @new_waves.each do |new_wave|
        new_wave.update_attribute(:wave_number, counter)
        counter = counter + 1
      end

      respond_to do |format|
        format.html { redirect_to waves_url, notice: "Waves were successfully updated"}
      end
    end

  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wave
      @wave = Wave.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wave_params
      params.require(:wave).permit(:wave_number, :start_time)
    end
end

app/helpers/waves_helper.rb
module WavesHelper
end

app/views/waves/_form.html.erb
<%= form_for(@wave) do |f| %>
  <% if @wave.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wave.errors.count, "error") %> prohibited this wave from being saved:</h2>

      <ul>
      <% @wave.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :wave_number %><br>
    <%= f.number_field :wave_number %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.datetime_select :start_time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/waves/edit.html.erb
<h1>Editing Wave</h1>

<%= render 'form' %>

<%= link_to 'Show', @wave %> |
<%= link_to 'Back', waves_path %>

app/views/waves/index.html.erb
<h1 class = "fronttitle">Listing Waves</h1>

<%= form_for(@wave, remote: true) do |f| %>
  <% if @wave.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wave.errors.count, "error") %> prohibited this wave from being saved:</h2>

      <ul>
      <% @wave.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<!--
  <div class="field">
    <%= f.label :wave_number %><br>
    <%= f.number_field :wave_number %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br>
    <% Time.zone = "Singapore" %>
    <%= f.datetime_select :start_time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
-->
<% end %>


<%= button_to 'Undo', '/waves/undolist', :method => "get" %>
<%= button_to 'Update Numbers', '/waves/update_nums', :method => "get", remote: true %> 
<p id="notice"><%= notice %></p>
<br>


<table>
  <thead>
    <tr>
      <th>Wave number</th>
      <th>Start time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @waves.sort_by { |x| [x.wave_number] }.reverse.each do |wave| %>
      <tr>
        <td><%= wave.wave_number %></td>
        <% Time.zone = "Singapore" %>
        <td><%= wave.start_time %></td>
        <td><%= link_to 'Show', wave %></td>
        <td><%= link_to 'Edit', edit_wave_path(wave) %></td>
        <td><%= link_to 'Destroy', wave, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<br>
<h2 class = "fronttitle">Instructions</h2>
<p class="instructions">FOR START TIMER</p>
<p class="instructions">1) Work with the TAGGERS to release each wave smoothly. Only release a wave when you know the TAGGERS have completed tagging that wave.</p>
<p class="instructions">To prevent an abrupt start to the race, make use of the timer which will be shown to the runners and release the wave when the timer hits 0.</p>
<p class="instructions">2) Tap "=" when you release the wave to record the timing for the Wave.</p>

<h2 class = "fronttitle">Problems</h2>
<p class="instructions">1) IN CASE YOU TAPPED "=" TWICE: Delete the wrong wave by clicking "Destroy"</p>
<p class="instructions">2) IN CASE YOU DELETED A WRONG WAVE: Click "Undo" and restore the wave you deleted</p>
<br>
<br>

<!--<%= link_to 'New Wave', new_wave_path %>-->

app/views/waves/new.html.erb
<h1>New Wave</h1>

<%= render 'form' %>

<%= link_to 'Back', waves_path %>

app/views/waves/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Wave number:</strong>
  <%= @wave.wave_number %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @wave.start_time %>
</p>

<%= link_to 'Edit', edit_wave_path(@wave) %> |
<%= link_to 'Back', waves_path %>

app/views/waves/undolist.html.erb
<h1> Undo List </h1>

<h1>Listing Waves</h1>

<table>
  <thead>
    <tr>
      <th>Wave number</th>
      <th>Start time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @waves.each do |wave| %>
      <tr>
        <td><%= wave.wave_number %></td>
        <td><%= wave.start_time %></td>
<!--        <td><%= link_to 'Show', wave %></td> -->

        <td><%= link_to 'Undo Deletion', "/waves/#{wave.id}/undo_deletion", method: :patch, data: { confirm: 'Are you sure?' } %></td>
<!--        <td><%= link_to 'Destroy', "/waves/#{wave.id}/really_delete", method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>